version: '3.9'
services:
    api:
        build:
            context: .
        command: ['npm', 'test']
        env_file:
            - docker.env
        ports:
            - 4000:4000
        depends_on:
            db:
                condition: service_healthy
    db:
        image: postgres:15.3-bookworm
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=catchemall
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 5s
            timeout: 5s
            retries: 5
        ports:
            - '5432:5432'
