# fly.toml app configuration file generated for catchemall-web-api on 2023-12-31T15:59:20+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "catchemall-web-api"
primary_region = "ams"

[build]
dockerfile = "Dockerfile"

[http_service]
internal_port = 4000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[env]
EXPIRES_IN = '4h'
ENV = 'PROD'
DAILY_POKEMON_NO = '5'
CATCH_CHANCE = '0.5'

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024
