version: '3.9'
services:
    ui:
        image: ${REPOSITORY_NAME}/catchemall-ui:latest
        ports:
            - 9138:80
        deploy:
            rollback_config:
                failure_action: pause
                monitor: 5s
                parallelism: 1
            restart_policy:
                condition: any
                delay: 3s
            update_config:
                monitor: 5s
                failure_action: rollback
                delay: 5s
                parallelism: 1
                order: start-first
    api:
        image: ${REPOSITORY_NAME}/catchemall-api:latest
        ports:
            - 9139:4000
        configs:
            - source: catchemall-api-v2.conf
              target: app/.env
        deploy:
            rollback_config:
                failure_action: pause
                monitor: 5s
                parallelism: 1
            restart_policy:
                condition: any
                delay: 3s
            update_config:
                monitor: 5s
                failure_action: rollback
                delay: 5s
                parallelism: 1
                order: start-first
configs:
    catchemall-api-v2.conf:
        external: true
